[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.SPEEDFACTOR = 1"
position = "after"
payload = "initSteamodded()"
match_indent = true

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
	"core/core.lua",
	"core/StackTracePlus.lua",
	"core/utils.lua",
	"core/overrides.lua",
	"core/game_object.lua",
	"debug/debug.lua",
	"core/compat_0_9_8.lua",
	"loader/loader.lua",
]
