[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

### Language API

# Game:set_language()
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "G.SETTINGS.language = 'en-us'"
position = 'before'
payload = 'self.temp_language = self.SETTINGS.language'
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "self.LANG = self.LANGUAGES[self.SETTINGS.language] or self.LANGUAGES['en-us']"
position = 'before'
payload = 'if self.temp_language then self.SETTINGS.language = self.temp_language end'
match_indent = true


[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "local localization = love.filesystem.getInfo('localization/'..G.SETTINGS.language..'.lua')"
position = 'at'
payload = "local localization = self.LANG.full_path and NFS.getInfo(self.LANG.full_path) or love.filesystem.getInfo('localization/'..G.SETTINGS.language..'.lua')"
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "self.localization = assert(loadstring(love.filesystem.read('localization/'..G.SETTINGS.language..'.lua')))()"
position = 'at'
payload = "self.localization = assert(loadstring(self.LANG.full_path and NFS.read(self.LANG.full_path) or love.filesystem.read('localization/'..G.SETTINGS.language..'.lua')))()"
match_indent = true
