[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Misprint-like description
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Misprint' then"
position = "before"
payload = '''
elseif self.ability.name == 'cry-Error' then
    main_start = {
        {n=G.UIT.O, config={object = DynaText({string = cry_error_operators, colours = {G.C.DARK_EDITION,},pop_in_rate = 9999999, silent = true, random_element = true, pop_delay = 0.30, scale = 0.32, min_cycle_time = 0})}},
        {n=G.UIT.O, config={object = DynaText({string = cry_error_numbers, colours = {G.C.DARK_EDITION,},pop_in_rate = 9999999, silent = true, random_element = true, pop_delay = 0.33, scale = 0.32, min_cycle_time = 0})}},
        {n=G.UIT.O, config={object = DynaText({string = cry_error_msgs,
        colours = {G.C.UI.TEXT_DARK},pop_in_rate = 9999999, silent = true, random_element = true, pop_delay = 0.4011, scale = 0.32, min_cycle_time = 0})}},
    }
'''
match_indent = true

