[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# replace music with low-res Funkytown when Jimball is here
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "(G.STATE == G.STATES.SPLASH and '') or"
position = "after"
payload = "(next(find_joker('cry-Jimball')) and Cryptid_config.Cryptid.jimball_music and 'cry_music-Jimball') or"
match_indent = true